version: "3.8"
services:
  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5433/webMagazine
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
  postgres:
    container_name: postgres
    image: postgres:13.4
    ports:
      - "5433:5433"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: webMagazine
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jena.zubova.03@mail.ru
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    db-data:
    pgadmin-data: